return {
    DoubleExperience = {
        Name = "2x Experience",
        Description = "Double the experience you gain when you defeat mobs. Stacks with Gamepass.",
        CanBuy = true,
        StateName = "Multiplier_Experience",
        StateValue = 2,
        CashPrice_1 = 1000,
        CashPrice_2 = 5000,
        Duration_1 = 600,
        Duration_2 = 3600,
    },

    DoubleCash = {
        Name = "2x Cash",
        Description = "Double your money! Stacks with Gamepass.",
        CanBuy = true,
        StateName = "Multiplier_Cash",
        StateValue = 2,
        CashPrice_1 = 1000,
        CashPrice_2 = 5000,
        Duration_1 = 600,
        Duration_2 = 3600,
    },

    DoubleSoulOrbs = {
        Name = "2x Soul Orbs",
        Description = "Double Soul Orbs! Stacks with Gamepass.",
        CanBuy = true,
        StateName = "Multiplier_Orbs",
        StateValue = 2,
        CashPrice_1 = 1000,
        CashPrice_2 = 5000,
        Duration_1 = 600,
        Duration_2 = 3600,
    },

    FastWalker = {
        Name = "Fast Walker",
        Description = "+5 Walkspeed. Stacks with your stand bonus.",
        CanBuy = true,
        StateName = "WalkSpeed",
        StateValue = 10,
        CashPrice_1 = 1000,
        CashPrice_2 = 5000,
        Duration_1 = 600,
        Duration_2 = 3600,
    },
    
    ItemFinder = {
        Name = "Item Finder",
        Description = "You can use the item finder. If you buy the Gamepass, boosts you find will never be this one.",
        CanBuy = false,
        StateName = nil, 
        StateValue = nil,
        CashPrice_1 = nil,
        CashPrice_2 = nil,
        Duration_1 = nil,
        Duration_2 = nil,
    },
}